name: deploy beta

on:
  push:
    branches:
      - master
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATAFILE_ID: rudnik
      DATAFILE_LANGUAGE: pl
      DATAFILE_POSITION: 3

    steps:
      - name: Checkout database-tools
        uses: actions/checkout@v3
        with:
          repository: opentouristics/database-tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout datafile repo
        uses: actions/checkout@v3
        with:
          repository: opentouristics/datafile-${{ env.DATAFILE_ID }}
          path: opentouristics/datafile-${{ env.DATAFILE_ID }}
          lfs: true

      - name: Create service account file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: ${{ github.workspace }}
          fileName: key.json
          encodedString: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 }}

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install database-tools
        run: make

      - name: publish
        run: ./publish "$DATAFILE_ID" "$DATAFILE_LANGUAGE" "$DATAFILE_POSITION"
