name: deploy prod

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy datafile
        uses: otwartaturystyka/deploy-datafile-action@v1
        with:
          id: rudnik
          position: 3
          prod: true
          service-account-key-base64: ${{ secrets.SERVICE_ACCOUNT_KEY_BASE64 }}
